"""The two guards must compile the SAME patterns, and nothing checked it.

`go/internal/guard/patterns_gen.go` is generated from this file's Python
source. Nothing ran the generator, nothing compared the results, and nothing
failed when the two drifted — so when the vault patterns gained
`\\.doublure/` and `\\.anonshield/` during the state-directory rename, the Go
binary kept the three it already had.

The consequence was not cosmetic. `open-domains.txt` lives in that directory
and is the only rule in the system that OPENS a network destination. Under the
Go binary the agent could write it, then reach the domain it had just opened —
the exact anti-pattern the round-19 hardening exists to prevent.

**The test that was supposed to cover the rename passed anyway**, because it
targeted `vault.db` and `anon_secret_key`: the two file names that match
patterns of their OWN. It proved the file names, never the directory. A pass
obtained for the wrong reason is not a pass.

So this compares the LISTS rather than re-running the generator: no repository
file is written, and what it pins is the property that matters — the same
patterns on both sides — rather than the freshness of a build artefact.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

RACINE = Path(__file__).resolve().parents[1]
GENERE = RACINE / "go" / "internal" / "guard" / "patterns_gen.go"

#: `(?i)` est ajouté par le générateur : la comparaison porte sur le motif.
_INSENSIBLE = "(?i)"


def _regles_go(nom: str) -> list[str]:
    """Motifs compilés dans une liste de règles du fichier généré."""
    source = GENERE.read_text(encoding="utf-8")
    debut = source.index(f"var {nom} = []")
    fin = source.index("\n}\n", debut)
    bloc = source[debut:fin]
    motifs = re.findall(r"regexp\.MustCompile\(`([^`]*)`\)", bloc)
    return [m[len(_INSENSIBLE):] if m.startswith(_INSENSIBLE) else m
            for m in motifs]


def test_the_vault_patterns_are_the_same_on_both_sides():
    """C'est la seule règle du garde dont l'échec est SILENCIEUX : un motif
    absent d'un côté n'a aucun symptôme jusqu'à ce qu'on s'en serve."""
    from hooks.pretooluse_guard import VAULT_PATTERNS

    assert set(_regles_go("vaultRules")) == set(VAULT_PATTERNS)


def test_the_generated_file_says_it_is_generated():
    """Un fichier édité à la main diverge à la prochaine génération, sans
    conflit et sans bruit."""
    assert "Code generated by gen_patterns.py" in GENERE.read_text(
        encoding="utf-8")[:200]


@pytest.mark.parametrize("liste", ["vaultRules", "sensitiveFileRules", "denyRules"])
def test_no_rule_list_is_empty(liste):
    """Une liste vide compile, se teste vert sur tout ce qui ne la concerne
    pas, et n'interdit plus rien."""
    assert _regles_go(liste), liste
