// Code generated by gen_patterns.py — DO NOT EDIT.
//
// The patterns come from the Python hook, which stays the single source of
// truth until it is retired. Regenerate with:
//
//	uv run python go/internal/guard/gen_patterns.py
//
// Lookaround assertions were stripped (RE2 has none) and re-implemented as
// named verifiers in patterns.go. The generator ABORTS if a pattern loses an
// assertion without a verifier, so a condition cannot be dropped silently.
package guard

import "regexp"

// rule is a pattern plus the conditions RE2 cannot express.
//
// marks holds the capture-group number of each stripped assertion, in the
// order they appeared. The group matches empty AT the assertion's position, so
// a verifier reads the text exactly where the assertion looked instead of
// counting characters back from a group boundary.
type rule struct {
	re     *regexp.Regexp
	verify func(text string, loc, marks []int) bool
	marks  []int
	reason string
}

const (
	vaultReason         = `accès au coffre de pseudonymisation ou à sa clé maître (le lire annulerait la protection)`
	sensitiveFileReason = `accès à un fichier de credentials ou de clés privées`
)

// Files of the ssh key directory that are PUBLIC by nature: refusing them
// stopped an agent from listing a fingerprint or reading a known-hosts file.
var sshPublicRe = regexp.MustCompile(`\.ssh/(config|known_hosts\w*|authorized_keys|[\w-]+\.pub)\b`)

var sshPrivateRe = regexp.MustCompile(`\.ssh/(id_\w+|identity)\b()`)

// lookaround réimplémenté : (?!\.pub)
var sshPrivateVerify = sshPrivateExcludingPub
var sshPrivateVerifyMarks = []int{2}

var vaultRules = []rule{
	{
		re: regexp.MustCompile(`(?i)\.doublure/`),
	},
	{
		re: regexp.MustCompile(`(?i)\.anonshield/`),
	},
	{
		re: regexp.MustCompile(`(?i)\.local/state/anonproxy`),
	},
	{
		re: regexp.MustCompile(`(?i)anon_secret_key`),
	},
	{
		re: regexp.MustCompile(`(?i)vault\.db`),
	},
}

var sensitiveFileRules = []rule{
	{
		re:     regexp.MustCompile(`(?i)()()\.env([.\-]()[\w-]+)?($|[\s'\"|>;&)\],])`),
		verify: envFile,
		marks:  []int{1, 2, 4},
		// lookaround réimplémenté : (?<!process) (?<!\.meta) (?!(example|sample|template|dist|schema)\b)
	},
	{
		re:     regexp.MustCompile(`(?i)(^|[\s/'\"=(])env\.()[\w-]+($|[\s'\"|>;&)\],])`),
		verify: envDotFile,
		marks:  []int{2},
		// lookaround réimplémenté : (?!(example|sample|template|dist|schema)\b)
	},
	{
		re: regexp.MustCompile(`(?i)\.aws/credentials`),
	},
	{
		re: regexp.MustCompile(`(?i)\.kube/config`),
	},
	{
		re: regexp.MustCompile(`(?i)\bkubeconfig\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.ssh(/|$|\b)`),
	},
	{
		re: regexp.MustCompile(`(?i)\.gnupg(/|$|\b)`),
	},
	{
		re: regexp.MustCompile(`(?i)/etc/ssl/private(/|$)`),
	},
	{
		re: regexp.MustCompile(`(?i)\bid_(rsa|dsa|ecdsa|ed25519)\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.netrc\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.git-credentials\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.docker/config\.json`),
	},
	{
		re: regexp.MustCompile(`(?i)\.npmrc\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.pypirc\b`),
	},
	{
		re: regexp.MustCompile(`(?i)secrets?[\w-]*\.(ya?ml|json|env|txt|conf|toml|ini)\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.(pem|key|p12|pfx|ppk|der|jks|keystore|pkcs12)\b`),
	},
	{
		re: regexp.MustCompile(`(?i)/proc/[^/\s]+/environ`),
	},
	{
		re: regexp.MustCompile(`(?i)\.envrc\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\bkubecfg\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\bterraform\.tfstate(\.backup)?\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\.tfstate\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\bcredentials?\.(json|ya?ml|ini|conf)\b`),
	},
	{
		re: regexp.MustCompile(`(?i)\bservice[-_]account[\w-]*\.json\b`),
	},
}

var denyRules = []rule{
	{
		re:     regexp.MustCompile(`(?i)\b(kubectl|kubecolor|oc|k|kc)\b[^|;&]*\b(get|describe)\b[^|;&]*\bsecret`),
		reason: `lecture de secrets Kubernetes en clair`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(kubectl|oc|k|kc)\b[^|;&]*\b(exec|cp)\b`),
		reason: `kubectl exec/cp permet de lire le jeton de compte de service monté dans le pod`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(kubectl|oc|k|kc)\b[^|;&]*\bcreate\b[^|;&]*\btoken\b`),
		reason: `émission d'un jeton Kubernetes`,
	},
	{
		re:     regexp.MustCompile(`(?i)/(var/)?run/secrets/`),
		reason: `montage de secrets (jeton de compte de service)`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bterraform\b[^|;&]*\b(state|console|show)\b`),
		reason: `l'état Terraform contient des secrets`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bterraform\b[^|;&]*\boutput\b()`),
		verify: terraformOutput,
		marks:  []int{1},
		// lookaround réimplémenté : (?![^|;&]*-json\s+\w)
		reason: `les sorties Terraform peuvent être sensibles`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(aws|gcloud|az|gh)\b[^|;&]*\b(get-session-token|print-access-token|get-token|get-access-token|print-identity-token|assume-role|export-credentials|sso|application-default)\b`),
		reason: `récupération de jeton ou de credentials cloud`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bgh\b[^|;&]*\b(auth\b[^|;&]*\btoken|secret\b)`),
		reason: `jeton ou secrets GitHub`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bhelm\b[^|;&]*\bget\b[^|;&]*\b(values|all|manifest)\b`),
		reason: `les values Helm contiennent des secrets`,
	},
	{
		re:     regexp.MustCompile(`(?i)-----BEGIN [A-Z ]*PRIVATE KEY-----`),
		reason: `clé privée en clair dans la commande`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bgpg\b[^|;&]*--export-secret-keys`),
		reason: `export de clé privée GPG`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bsecurity\b[^|;&]*\bfind-generic-password\b`),
		reason: `extraction du trousseau`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bps\b[^|;&]*(\bauxe\b|\beww\b|-\w*e\w*\b[^|;&]*\benviron\b|\benviron\b)`),
		reason: `l'environnement des autres processus (ps) expose leurs jetons`,
	},
	{
		re:     regexp.MustCompile(`(?i)/proc/[^/\s]+/(environ|cmdline)`),
		reason: `environnement d'un autre processus`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(gdb|strace|ltrace|lldb)\b[^|;&]*\s-p\b`),
		reason: `attachement à un processus vivant`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bsystemctl\b[^|;&]*\b(show-environment|show\b[^|;&]*Environment)\b`),
		reason: `environnement des unités systemd`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bdocker\b[^|;&]*\binspect\b`),
		reason: `docker inspect expose l'environnement d'un conteneur`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bgit\b\s+config\b()`),
		verify: gitConfig,
		marks:  []int{1},
		// lookaround réimplémenté : (?![^|;&]*\buser\.(name|email)\b)
		reason: `la configuration git peut contenir un jeton dans une URL de remote`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bgit\b[^|;&]*\bremote\b[^|;&]*(-v|get-url)`),
		reason: `les remotes git peuvent porter un jeton`,
	},
	{
		re:     regexp.MustCompile(`(?i)\.git/config\b`),
		reason: `la config du dépôt peut contenir un jeton`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bcrontab\b\s+-l\b`),
		reason: `les tâches planifiées portent souvent des secrets`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(kubectl|oc|k|kc)\b[^|;&]*\b(port-forward|proxy)\b`),
		reason: `un tunnel vers le cluster contourne le proxy (D9)`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bgh\b\s+api\b`),
		reason: "`gh api` appelle GitHub directement (D9)",
	},
	{
		re:     regexp.MustCompile(`(?i)\bdocker\b[^|;&]*\brun\b[^|;&]*-v\s*[^\s:]*(\.ssh|\.aws|\.kube|\.gnupg|/etc/ssl)`),
		reason: `montage d'un répertoire de secrets dans un conteneur`,
	},
	{
		re:     regexp.MustCompile(`(?i)(^|[|;&\s])(\.|source)\s+(/tmp/|/dev/|/var/tmp/)`),
		reason: `exécution d'un script depuis un répertoire temporaire : contenu non analysable`,
	},
	{
		re:     regexp.MustCompile(`(?i)\$HISTFILE\b`),
		reason: `l'historique de shell contient des secrets saisis`,
	},
	{
		re:     regexp.MustCompile(`(?i)\.(bash|zsh|sh)_history\b`),
		reason: `l'historique de shell contient des secrets saisis`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(BASH_ENV|SHELLOPTS|BASH_FUNC_\w*|LD_PRELOAD|LD_AUDIT|PYTHONSTARTUP|PERL5OPT|RUBYOPT)\s*=\s*\S`),
		reason: `affectation qui fait exécuter du code depuis un chemin non analysable`,
	},
	{
		re:     regexp.MustCompile(`(?i)\$\{[^}]*@P\}`),
		reason: "l'expansion de prompt (`@P`) exécute les substitutions que la variable contient : son contenu n'est pas analysable avant exécution",
	},
	{
		re:     regexp.MustCompile(`(?i)\bprintf\s+(?:-\S+\s+)*-v\s+(PS[0-9]|PROMPT_COMMAND)\b`),
		reason: `construction d'une variable dont la valeur est exécutée comme une commande`,
	},
	{
		re:     regexp.MustCompile(`(?i)\b(PROMPT_COMMAND|command_not_found_handle)\s*=\s*\S`),
		reason: `affectation d'une variable dont la valeur est exécutée comme une commande`,
	},
	{
		re:     regexp.MustCompile("(?i)\\bPS[04]\\s*=[^|;&\\n]*(\\$\\(|`)"),
		reason: `affectation d'une variable dont la valeur est exécutée comme une commande`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bENV\s*=\s*[^\s|;&]*/`),
		reason: `affectation qui fait exécuter du code depuis un chemin non analysable`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bNODE_OPTIONS\s*=[^|;&\n]*(--require|--import|\s-r\b)`),
		reason: `affectation qui fait exécuter du code depuis un chemin non analysable`,
	},
	{
		re:     regexp.MustCompile(`(?i)\.local/state(/[^/\s]*)*/\*`),
		reason: `accès générique au répertoire d'état (coffre)`,
	},
	{
		re:     regexp.MustCompile(`(?i)\bfind\b[^|;&]*\.local/state\b`),
		reason: `énumération du répertoire d'état (coffre)`,
	},
}
